<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Mail</strong> module configuration' => '',
    'Allow others to send you private messages' => '',
    'Allow users to start new conversations' => '',
    'Conversation' => '',
    'Created At' => '',
    'Created By' => 'تم وضعه بواسطة',
    'Edit message...' => '',
    'Is Originator' => '',
    'Last Viewed' => '',
    'Leave fields blank in order to disable a restriction.' => '',
    'Max messages allowed per day' => '',
    'Max number of messages allowed for a new user per day' => '',
    'Max number of new conversations allowed for a new user per day' => '',
    'Max number of new conversations allowed for a user per day' => '',
    'Message' => 'الرسالة',
    'Messages' => 'الرسائل',
    'Receive Notifications when someone opens a new conversation.' => '',
    'Receive Notifications when someone sends you a message.' => '',
    'Receive private messages' => '',
    'Seperate restrictions for new users' => '',
    'Show menu item in top Navigation' => '',
    'Start new conversations' => '',
    'This user is already participating in this conversation.' => '',
    'Title' => 'العنوان',
    'Today' => '',
    'Until a user is member since (days)' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User' => 'المستخدم',
    'Write a message...' => '',
    'You are not allowed to start a conversation with this user.' => '',
    'You\'ve exceeded your daily amount of new conversations.' => '',
    'Delete' => 'حذف',
    'Edit' => 'تحرير',
    'Save' => 'حفظ',
    'Toggle message entry menu' => 'تبديل قائمة إدخال الرسائل',
];
