<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add user' => '@@اضافة مستخدم@@',
    'Send' => '@@ارسل@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>تأكيد</strong> حذف المحادثة',
    '<strong>Confirm</strong> leaving conversation' => '<strong>تأكيد</strong> مغادرة المحادثة',
    '<strong>Confirm</strong> message deletion' => '<strong>تأكيد</strong> حذف الرسالة',
    'Add users to conversation' => 'إضافة مستخدمين إلى المحادثة',
    'Cancel' => 'الغاء',
    'Delete' => 'حذف',
    'Delete conversation' => 'حذف المحادثة',
    'Do you really want to delete this conversation?' => 'هل تريد حذف هذه المحادثة؟',
    'Do you really want to delete this message?' => 'هل تريد حذف هذه الرسالة؟',
    'Do you really want to leave this conversation?' => 'هل تريد مغادرة هذه المحادثة؟',
    'Leave' => 'مغادرة',
    'Leave conversation' => 'اترك محادثة',
    'There are no messages yet.' => 'لا توجد رسائل',
];
